---
methods:
  privacy.limitAdTracking:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('privacySettings');
        console.log("*** value of ccs.limitAdTracking in yaml----", ccs.limitAdTracking);
        return ccs.limitAdTracking;
      }
  advertising.policy: 
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('privacySettings');
        console.log("*** value of policy in yaml----", ccs);
        return ccs;
      }
  privacy.setLimitAdTracking:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('privacySettings');
        console.log(`Set limitAdTracking params =>`, params);
        ccs.limitAdTracking = params && params.value;
        ctx.set('privacySettings', ccs, '~A');
        console.log(`*** Updated the limitAdTracking value for ccs limitAdTracking ***`);
        const result = ctx.get('privacySettings');
        const msg = 'Post trigger privacy.setLimitAdTracking';
        console.log("value of result inside yaml ",result);
        console.log("value of msg inside in yaml",msg);
        ctx.sendBroadcastEvent('advertising.onPolicyChanged', result, msg);
        return null;
      }
  advertising.setSkipRestriction:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('privacySettings');
        console.log(`Set skipRestriction params =>`, params);
        ccs.skipRestriction = params && params.value;
        ctx.set('privacySettings', ccs, '~A');
        console.log(`*** Updated the skipRestriction value for ccs skipRestriction ***`);
        const result = ctx.get('privacySettings');
        const msg = 'Post trigger advertising.setSkipRestriction';
        console.log("value of result inside yaml ",result);
        console.log("value of msg inside in yaml",msg);
        ctx.sendBroadcastEvent('advertising.onPolicyChanged', result, msg);
        return null;
      }