---
methods:
  voiceguidance.enabled:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('voiceGuidanceSettings');
        return ccs.enabled;
      }    
  voiceguidance.setEnabled:
    response: |
      function f(ctx, params) {
        const ccs = ctx.get('voiceGuidanceSettings');
        ccs.enabled=params.value
        ctx.set('voiceGuidanceSettings',ccs)
        const result = ctx.get('voiceGuidanceSettings');
        const msg = 'Post trigger for voiceguidance.setEnabled';
        ctx.sendEvent('accessibility.onVoiceGuidanceSettingsChanged', result, msg);
        return null;
      }
  accessibility.voiceGuidanceSettings:
    response: |
      function f(ctx, params) {
        // Getter called... Return our stashed value, per last setter call
        const ccs = ctx.get('voiceGuidanceSettings');
        return ccs;
      }
