# This workflow will do a build of MFOS and run all unit tests. It will then run a coverage analysis against a threshold

name: PR Unit Tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches: [ main ]

jobs:
  unitTests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js $${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Tests
      run: |
        cd server; \
        npm install; \
        cp src/.mf.config.SAMPLE.json src/.mf.config.json; \
        npm run test
